name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  semver_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Generate release PR or tag
        id: release
        uses: googleapis/release-please-action@v4
        with:
          release-type: rust
          include-component-in-tag: false
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
