name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  semver_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Generate release PR or tag
        uses: googleapis/release-please-action@v4
        with:
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json
