name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  semver_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      release_tag: ${{ steps.release.outputs.tag_name }}

    steps:
      - name: Generate release PR or tag
        id: release
        uses: googleapis/release-please-action@v4
        with:
          release-type: rust
          include-component-in-tag: false
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}

  trigger_docker_publish:
    needs: semver_release
    if: needs.semver_release.outputs.release_created == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Docker publish workflow
        run: gh workflow run "Publish Docker Image" --ref ${{ needs.semver_release.outputs.release_tag }}
        env:
          GH_TOKEN: ${{ secrets.RELEASE_PLEASE_TOKEN }}
